apiVersion: v1
kind: ConfigMap
metadata:
 name: aws-auth
 namespace: kube-system
data:
 mapRoles: |
   - rolearn:  arn:aws:iam::111761281282:role/clusternodes-NodeInstanceRole-1QOT48BYY14Q1
     username: system:node:{{EC2PrivateDNSName}}
     groups:
        - system:bootstrappers
        - system:nodes
